name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
 
jobs:
  build_backend:
    name: Build Backend
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: zimskasola
          POSTGRES_USER: postgres_user
          POSTGRES_PASSWORD: postgres_pwd
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: maven
  
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests
        working-directory: Backend

      - name: Upload resulting Build package
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: Backend/target


  BE-docker-image-delivery:
    name: BE Docker Image Delivery
    runs-on: ubuntu-latest
    needs: build_backend

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v4
        with:
          name: Package
          path: Backend/target/

      - name: Generate image tag
        id: date
        run: echo "::set-output name=date::$(date +%Y%m%d-%H%M%S)"

      - name: Docker build
        run: docker build -t anjalecnik/zimskasola-qrks:$TAG_NAME -f Backend/src/main/docker/Dockerfile.jvm ./Backend
        env:
          TAG_NAME: CD-${{ steps.date.outputs.date }}

      - name: Retag to latest
        run: docker tag anjalecnik/zimskasola-qrks:$TAG_NAME anjalecnik/zimskasola-qrks:latest
        env:
          TAG_NAME: CD-${{ steps.date.outputs.date }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker push
        run: docker push anjalecnik/zimskasola-qrks:$TAG_NAME && docker push anjalecnik/zimskasola-qrks:latest
        env:
          TAG_NAME: CD-${{ steps.date.outputs.date }}
